# Generated by Django 2.2.12 on 2021-06-09 23:18

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosociality_group', to='otree.Session')),
            ],
            options={
                'db_table': 'prosociality_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prosociality_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'prosociality_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('punish_your_punisher', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='\n                            ¿Qué tan dispuesto\n                            está usted a castigar a\n                            alguien que lo(a) trata a\n                            usted injustamente,\n                            incluso cuando existan\n                            riesgos para usted de\n                            sufrir consecuencias\n                            personales?')),
                ('punish_others_punisher', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='\n                            ¿Qué tan dispuesto(a)\n                            está usted a castigar a\n                            alguien que trata a los\n                            demás injustamente,\n                            incluso cuando existan\n                            riesgos para usted de\n                            sufrir consecuencias\n                            personales?')),
                ('donate_without_reward', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='\n                            ¿Qué tan dispuesto(a)\n                            está usted a hacer\n                            donaciones a causas\n                            benéficas sin esperar\n                            nada a cambio?')),
                ('reciprocity', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='\n                            Cuando alguien me hace un\n                            favor, estoy dispuesto a\n                            devolverlo.')),
                ('revenge', otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='\n                            Si me tratan muy\n                            injustamente, tomaré\n                            revancha en la primera\n                            ocasión, incluso aunque deba\n                            pagar un costo por ello.')),
                ('stranger_payback', otree.db.models.IntegerField(choices=[(1, 'No, no le entregaría ningún obsequio'), (2, 'El obsequio que cuesta 2 Soles'), (3, 'El obsequio que cuesta 4 Soles'), (4, 'El obsequio que cuesta 6 Soles'), (5, 'El obsequio que cuesta 8 Soles'), (6, 'El obsequio que cuesta 10 Soles'), (7, 'El obsequio que cuesta 12 Soles'), (8, '(NS/NR)')], null=True, verbose_name='\n                            Por favor piense en que haría usted en la siguiente situación. Está en un área que no conoce mucho y se da cuenta que se ha\n                            perdido. Le pide orientación a un extraño. El extraño le ofrece llevarlo a su destino.\n                            \n                            Ayudarlo a usted le cuesta al extraño unos 8 Soles en total. Sin embargo, el extraño dice que no desea que usted le de dinero. Usted\n                            tiene seis obsequios. El obsequio más económico cuesta 2 Soles y el más costoso cuesta 12 Soles. ¿Le daría al extraño uno de los\n                            obsequios como agradecimiento?\n                            \n                            ¿Qué obsequio le entregaría?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prosociality.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosociality_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosociality_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosociality.Subsession')),
            ],
            options={
                'db_table': 'prosociality_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosociality.Subsession'),
        ),
    ]
