# Generated by Django 2.2.12 on 2021-04-03 16:40

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('prosociality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stranger_payback',
            field=otree.db.models.IntegerField(choices=[(1, 'No, no le entregaría ningún obsequio'), (2, 'El obsequio que cuesta 2 Soles'), (3, 'El obsequio que cuesta 4 Soles'), (4, 'El obsequio que cuesta 6 Soles'), (5, 'El obsequio que cuesta 8 Soles'), (6, 'El obsequio que cuesta 10 Soles'), (7, 'El obsequio que cuesta 12 Soles'), (8, '(NS/NR)')], null=True, verbose_name='\n                            Por favor piense en que haría usted en la siguiente situación. Está en un área que no conoce mucho y se da cuenta que se ha\n                            perdido. Le pide orientación a un extraño. El extraño le ofrece llevarlo a su destino.\n                            \n                            Ayudarlo a usted le cuesta al extraño unos 8 Soles en total. Sin embargo, el extraño dice que no desea que usted le de dinero. Usted\n                            tiene seis obsequios. El obsequio más económico cuesta 2 Soles y el más costoso cuesta 12 Soles. ¿Le daría al extraño uno de los\n                            obsequios como agradecimiento?\n                            \n                            ¿Qué obsequio le entregaría?'),
        ),
    ]
