# Generated by Django 2.2.12 on 2021-04-02 01:33

from django.db import migrations
import otree.currency
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='amount_offered',
        ),
        migrations.RemoveField(
            model_name='player',
            name='complex_mode',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_endowment',
        ),
        migrations.RemoveField(
            model_name='player',
            name='message',
        ),
        migrations.RemoveField(
            model_name='player',
            name='offer_accepted',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_amount_offered',
        ),
        migrations.AddField(
            model_name='group',
            name='amount_offered',
            field=otree.db.models.CurrencyField(choices=[(otree.currency.Currency('0'), otree.currency.Currency('0')), (otree.currency.Currency('1'), otree.currency.Currency('1')), (otree.currency.Currency('2'), otree.currency.Currency('2')), (otree.currency.Currency('3'), otree.currency.Currency('3')), (otree.currency.Currency('4'), otree.currency.Currency('4')), (otree.currency.Currency('5'), otree.currency.Currency('5')), (otree.currency.Currency('6'), otree.currency.Currency('6')), (otree.currency.Currency('7'), otree.currency.Currency('7')), (otree.currency.Currency('8'), otree.currency.Currency('8')), (otree.currency.Currency('9'), otree.currency.Currency('9')), (otree.currency.Currency('10'), otree.currency.Currency('10')), (otree.currency.Currency('11'), otree.currency.Currency('11')), (otree.currency.Currency('12'), otree.currency.Currency('12')), (otree.currency.Currency('13'), otree.currency.Currency('13')), (otree.currency.Currency('14'), otree.currency.Currency('14')), (otree.currency.Currency('15'), otree.currency.Currency('15')), (otree.currency.Currency('16'), otree.currency.Currency('16')), (otree.currency.Currency('17'), otree.currency.Currency('17')), (otree.currency.Currency('18'), otree.currency.Currency('18')), (otree.currency.Currency('19'), otree.currency.Currency('19')), (otree.currency.Currency('20'), otree.currency.Currency('20'))], null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='offer_accepted',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='round_payoff',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
