# Generated by Django 2.2.12 on 2021-04-02 01:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0002_auto_20210401_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='round_payoff',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
