# Generated by Django 2.2.12 on 2021-04-06 05:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0003_auto_20210401_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='acceptance_percent',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='avg_proposal',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='rejection_percent',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
    ]
