# Generated by Django 2.2.12 on 2021-04-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatum', '0004_auto_20210406_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='acceptance_percent',
        ),
        migrations.RemoveField(
            model_name='group',
            name='avg_proposal',
        ),
        migrations.RemoveField(
            model_name='group',
            name='rejection_percent',
        ),
    ]
