# Generated by Django 2.2.12 on 2021-06-09 23:18

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('baseIncome', otree.db.models.CurrencyField(null=True)),
                ('total_report', otree.db.models.CurrencyField(null=True)),
                ('total_contribution', otree.db.models.CurrencyField(null=True)),
                ('total_earnings', otree.db.models.CurrencyField(null=True)),
                ('individual_share', otree.db.models.CurrencyField(null=True)),
                ('temp', otree.db.models.IntegerField(null=True)),
                ('authority_ID', otree.db.models.IntegerField(null=True)),
                ('authority_multiply', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('auth_appropriate', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('total_reported_income', otree.db.models.CurrencyField(null=True)),
                ('appropriation', otree.db.models.CurrencyField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_effort2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'real_effort2_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_effort2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'real_effort2_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('audit2', otree.db.models.IntegerField(null=True)),
                ('transcribed_text', otree.db.models.LongStringField(null=True)),
                ('transcribed_text2', otree.db.models.LongStringField(null=True)),
                ('levenshtein_distance', otree.db.models.IntegerField(null=True)),
                ('ratio', otree.db.models.FloatField(null=True)),
                ('contribution', otree.db.models.CurrencyField(default=-1, null=True)),
                ('income', otree.db.models.CurrencyField(null=True)),
                ('spanish', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('done', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('transcriptionDone', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('orig_income', otree.db.models.CurrencyField(default=0, null=True)),
                ('refText', otree.db.models.LongStringField(null=True)),
                ('audit', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='real_effort2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_effort2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_effort2_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_effort2.Subsession')),
            ],
            options={
                'db_table': 'real_effort2_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_effort2.Subsession'),
        ),
    ]
