# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('baseIncome', otree.db.models.CurrencyField(null=True)),
                ('total_report', otree.db.models.CurrencyField(null=True)),
                ('total_contribution', otree.db.models.IntegerField(null=True)),
                ('total_earnings', otree.db.models.IntegerField(null=True)),
                ('individual_share', otree.db.models.FloatField(null=True)),
                ('temp', otree.db.models.IntegerField(null=True)),
                ('authority_ID', otree.db.models.IntegerField(null=True)),
                ('authority_multiply', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('auth_appropriate', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('total_reported_income', otree.db.models.CurrencyField(null=True)),
                ('appropriation', otree.db.models.IntegerField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_effort2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'real_effort2_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('transcribed_text', otree.db.models.LongStringField(null=True)),
                ('transcribed_text2', otree.db.models.LongStringField(null=True)),
                ('levenshtein_distance', otree.db.models.IntegerField(null=True)),
                ('ratio', otree.db.models.FloatField(null=True)),
                ('contribution', otree.db.models.IntegerField(default=-1, null=True)),
                ('income', otree.db.models.IntegerField(null=True)),
                ('spanish', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('done', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('transcriptionDone', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('payoff', otree.db.models.FloatField(null=True)),
                ('refText', otree.db.models.LongStringField(null=True)),
                ('audit', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='real_effort2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_effort2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_effort2_player', to='otree.Session')),
            ],
            options={
                'db_table': 'real_effort2_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_effort2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'real_effort2_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_effort2.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_effort2.Subsession'),
        ),
    ]
