# Generated by Django 2.2.12 on 2021-06-27 21:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='orig_income',
        ),
        migrations.AddField(
            model_name='group',
            name='appropriation_percent',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='authority',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='multiplier',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='penalty_percent',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='spanish',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='tax_percent',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='transcription_difficulty',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='transcription_required',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='treatment_tag',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='endowment',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='income_before_taxes',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='appropriation',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
    ]
