# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-05 06:34
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='audit2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='appropriation',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_contribution',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_earnings',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='contribution',
            field=otree.db.models.CurrencyField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='income',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='payoff',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
