# Generated by Django 2.2.12 on 2022-02-10 19:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='kept',
            field=otree.db.models.IntegerField(null=True, verbose_name='Si pudieras decidir cómo dividir los puntos (Participante 1), ¿con cuántos te quedarías? (desde 0 hasta 100)'),
        ),
    ]
