# Generated by Django 2.2.12 on 2021-04-29 04:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_tossing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chosen_app',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
