# Generated by Django 2.2.12 on 2021-05-07 01:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_tossing', '0002_player_chosen_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_is_lying',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
