# Generated by Django 2.2.12 on 2021-05-07 01:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_tossing', '0004_auto_20210506_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_is_lying',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
