# Generated by Django 2.2.12 on 2021-04-07 14:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0003_auto_20210401_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sent_amount_strategy',
            field=otree.db.models.CurrencyField(null=True, verbose_name='Si fueras el jugador 1, cuánto enviarías al Jugador 2 - Strategy'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
