# Generated by Django 2.2.12 on 2021-04-09 18:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0004_auto_20210407_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sent_back_amount_strategy',
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_12',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Si fueras el jugador B y recibieras 12 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_15',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], null=True, verbose_name='Si fueras el jugador B y recibieras 15 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_18',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], null=True, verbose_name='Si fueras el jugador B y recibieras 18 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_21',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21)], null=True, verbose_name='Si fueras el jugador B y recibieras 21 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_24',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True, verbose_name='Si fueras el jugador B y recibieras 24 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_27',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27)], null=True, verbose_name='Si fueras el jugador B y recibieras 27 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_3',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True, verbose_name='Si fueras el jugador B y recibieras 3 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_30',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], null=True, verbose_name='Si fueras el jugador B y recibieras 30 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_6',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True, verbose_name='Si fueras el jugador B y recibieras 6 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sent_back_amount_strategy_9',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, verbose_name='Si fueras el jugador B y recibieras 9 puntos, ¿cuánto enviarías de vuelta al Jugador A?'),
        ),
        migrations.AddField(
            model_name='player',
            name='trustee',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='trustor',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='sent_amount_strategy',
            field=otree.db.models.CurrencyField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, verbose_name='Si fueras el jugador A, ¿cuánto enviarías al Jugador B?'),
        ),
    ]
