# Generated by Django 2.2.12 on 2021-04-02 03:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='round_payoff',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='contribution',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
