# Generated by Django 2.2.12 on 2021-04-14 03:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods', '0003_auto_20210401_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='chosen_app',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
