# Generated by Django 2.2.12 on 2022-02-01 17:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods', '0003_auto_20220201_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='individual_share',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
