# Generated by Django 2.2.12 on 2022-02-01 17:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods', '0004_auto_20220201_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='round_payoff',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
